### ISSUE TITLE
Issue detecting "stopButton.png" at startup

### ISSUE THREAD

**Issue by snarfums** [yoelk/Instrumentino#8]
My environment: 
OS: Ubuntu v14.x
IDE: LiClipse v1.4.0.x (Eclipse variant with PyDev and other things pre-loaded)
Python: v2.7
Instrumentino: v1.08

Details: Installing/importing the instrumentino egg from LiClipse doesn't appear to have brought with "stopButton.png" file with it. 

Temporary workaround: It had to be manually copied from the instrumentino/instrumentino/resources folder to ~/.python-eggs/instrumentino-1.08-py2.7.egg-tmp/stopButton.png

Note: My guess is that this graphic is not included as a resource in the egg, I'm missing a configuration step, or using a different import method would include it?  If so I don't know how to fix it properly as I'm not familiar with python egg creation and ther are too many "ifs" on my side.

Thanks!

**Comment by snarfums** [comment]
Ah, it appears from the closed issues this has been an issue in the past.
Anyway, I'm not sure if you want to close or if there is another option (documentation, wish to build the resource into the egg for xyz import, etc. ) as it appears that there are some tools that do not import the egg the same.

If you (or anyone else) don't have the time I could look into fixing this via "fixing" the egg (if even possible?), I just haven't done any egg development before.

**Comment by yoelk** [comment]
Hi,
I'm pretty sure the egg file does include the stopButton graphics.

But anyway, it seems that you found a workaround now, right?
Let's leave it like that for now, as I'm currently working on Instrumentino
V2, in which Kivy will be used as the graphics platform.
If you're up to it, I could sure use some help doing that so give me a call
if you're interested.

Joel

**Comment by snarfums** [comment]
I might be able to carve some time on weekends to work on things.  I've never used Kivy before though.  Any idea when you planning to upload V2 that I could pull down?  Even if you uploaded a "non working" version as a dev branch and indicated/assigned some areas needing work I could see if I could make some useful contributions.  I'm assuming a new user front end would initially just be a direct port of the V1 layout and functionality.

**Comment by yoelk** [comment]
Hi, that's great!
And yes, for starters I want to port the existing Instrumentino to Kivy, so
it's mainly GUI tasks.
My first step was to create a screen layout that is divided to 3 resizable
parts, using two "Splitters" (see here for more details
<http://stackoverflow.com/questions/28689268/how-to-use-several-splitters-in-kivy>
)
I want to maximize the use of kvlang, Kivy's way of describing GUI design
(a bit like XML).
I did that (see attached code) but I'm stuck on something.
Do you see all of the duplicated code? For each splitter, I do all of these
initializations (max_size, min_size, size_hint, etc.).
What I'd like to do, is to combine the common code into a
CustomizedSplitter class.
The problem is that I couldn't make it work that way.
I've opened a stackoverflow question
<http://stackoverflow.com/questions/28684165/passing-information-from-child-class-to-parent-using-dynamic-classes-in-kvlang>
some weeks ago, and even put a bounty, but no one seems to know the
answer...

So this is where I'm stuck at the moment. Still in the beginning, but it's
important to do things right from the start.

Thanks, have a nice Easter,
Joel

**Comment by snarfums** [comment]
What version of Kivy and python are you using? 
I've just installed Kivy 1.8.0 (got a few of the built in examples working) and am using python 2.7.  Once I read more docs and work on a few more examples I'll see what I can do.

**Comment by yoelk** [comment]
I'm using Python 2.7 and Kivy 1.8 as well.
Yesterday I started reading this book <http://www.it-ebooks.info/book/3288/>
about kivy development.
I hope it will help me understand how I should use kvlang

**Comment by snarfums** [comment]
I had a lot to comment and it may "go long" so I submitted it as Issue #10 :)
