### ISSUE TITLE
Instrumentino/Controlino

### ISSUE THREAD

**Issue by chiccodoro** [yoelk/Instrumentino#9]
Hi Israel Joel,
I am planning to use your GUI called instrumentino, to get some data through the USB of the PC. I am using a set-up similar to this one https://cdn.sparkfun.com/assets/1/5/9/9/9/simple-redboard_levelShift_bb.png with an arduino micro. 
At the moment I use the arduino serial monitor to check sensor values, but I would like to replace it by using instrumentino.
I have no much experience in coding and GUI and I would like your help.
Therefore, I was wondering if you can help me how to configure instrumentino to read data from the USB and plot them on a chart. Do you have any example?
Thank you in advance,
Francesco.

**Comment by yoelk** [comment]
Hi Francesco,
Did you already read the documents in Instrumentino's GitHub repository?
You can find there a simple example for reading analog signals:
https://github.com/yoelk/Instrumentino/tree/master/documents/example_run_ArduinoPins.py

**Comment by chiccodoro** [comment]
Hi Isreal Joel,
I have downloaded everything from this site, including your example and documentations. 
I have few questions since things are not enough clear to me. I am not a Python or software expert :-)
1) Do you use your GUI done in Python directly to control the Arduino as in the example ArduinoPins.py?
2) Is there a possibility with your GUI to read only the content coming from the USB and plot it?
if answer to question 1) is negative and to 2) is positive. I think I am missing something in your code. 
3) Talking about your example ArduinoPins.py, in which part of the code you set the GUI to read from the USB? 
4) Why you need to declare this
# Arduino pins
pinAnalInA = 1
pinPwmOutA = 9
pinAnalInB = 2
pinPwmOutB = 10
5) Is it possible to have an explanation to how you built up your GUI, please? For instance, what this part of the code does
from __future__ import division
from instrumentino import Instrument
from instrumentino import cfg
from instrumentino.action import SysAction, SysActionParamTime, SysActionParamFloat, SysActionParamInt
from instrumentino.controllers.arduino import SysVarDigitalArduino, SysVarAnalogArduinoUnipolar
from instrumentino.controllers.arduino.pins import DigitalPins, AnalogPins

My intent is to use what you have done and adapting to my needs.
Thank you in advance for any help,
Francesco.

**Comment by yoelk** [comment]
1. I didn't understand the question
   I run the system description file using python. This brings up a GUI
   window for my custom system.
   2. Yes. In the example, this is exactly what I do.
   3. Instrumentino is a framework, that hides as much as possible from the
   users, so they don't need to take care of things like USB communication. If
   you're interested in its internals, browse the instrumentino code itself.
   Specifically, USB communication is handled in the Arduino class
   <https://github.com/yoelk/Instrumentino/blob/master/instrumentino/instrumentino/controllers/arduino/__init__.py>
   .
   4. These are Arduino pin declarations, to be used in the components. It
   is good coding practice to give names to variables instead of using numbers
   in the code.
   5. Please google it, as this is question is about Python and not
   Instrumentino.

As you see, it's important to know your way around Python to use
Instrumentino. I chose Python because its the easiest programming language
I know, but it still requires some effort in learning it.
Here is a good way to start <http://www.python-course.eu/>.

Also, please read the release article (PDF) in the documents folder in
GitHub.

Good luck!
Joel

**Comment by chiccodoro** [comment]
Hi Isreal Joel,
thank you for the time you took to reply to my questions.
I have read your paper entitled "Instrumentino: An-open source modular Python..." and it is very useful.
To the best of my knowledge, Instrumentino takes the control of the whole system (PIC, sensors, and so on). What I am going to try it is reading the data over the USB and plotting them. Therefore, I will have a look to point 3) of your answer as well as you manage the chart. 
I am going to leave the main functionalities inside the PIC without controlling it with the GUI.
Thanks,
Francesco.
